import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Importing Geist fonts from Google Fonts

const geistSans = Geist({

  // Setting CSS variable for Geist Sans font
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Importing Geist Mono font from Google Fonts
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component wrapping the entire application
export default function RootLayout({

  // Destructuring children prop

  // Type annotation for children prop
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Returning the HTML structure with applied fonts

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
// Applying Geist fonts and antialiasing to the body element